// packages/reactxy/src/components/menu/menu.tsx
/*
 * @Author: Chengbotao
 * @Date: 2022-10-17 00:09:40
 */
import React, {
  FC,
  createContext,
  useState,
  Children,
  cloneElement,
  FunctionComponentElement,
} from 'react';
import classNames from 'classnames';
import { SubMenuProps } from './subMenu';
import { MenuItemProps } from './menuItem';

type MenuMode = 'horizontal' | 'vertical';
type MenuSelectCallback = (selectedIndex: string) => void;

export interface MenuProps {
  defaultIndex?: string;
  className?: string;
  mode?: MenuMode;
  style?: React.CSSProperties;
  onSelect?: MenuSelectCallback;
  children?: React.ReactNode;
  defaultOpenSubMenus?: string[];
}

interface MenuContext {
  defaultOpenSubMenus?: string[];
  index: string;
  onSelect?: MenuSelectCallback;
  mode?: MenuMode;
}
export const menuContext = createContext<MenuContext>({ index: '0' });

const Menu: FC<MenuProps> = (props) => {
  const { className, defaultIndex, style, mode, children, defaultOpenSubMenus, onSelect } = props;

  const [currentActive, setCurrentActive] = useState(defaultIndex);
  const classes = classNames('xy-menu', className, {
    'xy-menu-vertical': mode === 'vertical',
    'xy-menu-horizontal': mode != 'vertical',
  });

  const handleClick = (index: string) => {
    setCurrentActive(index);
    onSelect && onSelect(index);
  };

  const passedContext: MenuContext = {
    mode,
    defaultOpenSubMenus,
    index: currentActive ?? '0',
    onSelect: handleClick,
  };

  const renderChildren = () => {
    return Children.map(children, (child, index) => {
      const childElement = child as
        | FunctionComponentElement<MenuItemProps>
        | FunctionComponentElement<SubMenuProps>;

      const { displayName } = childElement.type;
      if (displayName === 'MenuItem' || displayName === 'SubMenu') {
        return cloneElement(childElement, {
          index: index.toString(),
        });
      } else {
        console.warn('Warning: Menu has a child which is not a MenuItem component!');
      }
    });
  };
  return (
    <ul className={classes} style={style}>
      <menuContext.Provider value={passedContext}>{renderChildren()}</menuContext.Provider>
    </ul>
  );
};

Menu.defaultProps = {
  defaultIndex: '0',
  mode: 'vertical',
  defaultOpenSubMenus: [],
};

export default Menu;

// packages/vue3xy/src/components/menu/menu.vue
<!--
 * @Author: Chengbotao
 * @Date: 2023-01-28 22:31:08
-->
<template>
  <ul :class="classes" v-bind="$attrs">
    <slot></slot>
  </ul>
</template>

<script setup lang="ts">
import { computed, provide, ref, Ref} from "vue";
import classNames from "classnames";

defineOptions({
    name: 'XyMenu',
    inheritAttrs: false,
})

type MenuMode = 'horizontal' | 'vertical';
type MenuSelectCallback = (selectedIndex: string) => void;

interface MenuProps {
  defaultIndex?: string;
  className?: string;
  mode?: MenuMode;
  onSelect?: MenuSelectCallback;
  defaultOpenSubMenus?: string[];
}

interface ProvideOrInjectTyping {
  index: Ref<string>;
  mode?: MenuMode;
  onSelect?: MenuSelectCallback;
  defaultOpenSubMenus?: string[];
}

// Props
const props = withDefaults(defineProps<MenuProps>(), {
  defaultIndex: '0',
  mode: 'vertical',
  defaultOpenSubMenus: () => [],
});

// Emits

// data
const currentActive = ref(props.defaultIndex)

// computed
const classes = computed(() => {
  return classNames('xy-menu', props.className, {
    'xy-menu-vertical': props.mode === 'vertical',
    'xy-menu-horizontal': props.mode != 'vertical',
  });
});

// methods
const handleClick = (index: string) => {
  currentActive.value = index;
  props.onSelect && props.onSelect(index);
};

// provide
provide<ProvideOrInjectTyping>("context", {
  index: currentActive,
  onSelect: handleClick,
  mode: props.mode,
  defaultOpenSubMenus: props.defaultOpenSubMenus
})

// public 方法
defineExpose({})

</script>
