// packages/reactxy/src/components/autoComplete/autoComplete.tsx
/*
 * @Author: Chengbotao
 * @Date: 2022-11-23 16:08:19
 */
import React, {
  ChangeEvent,
  FC,
  KeyboardEvent,
  ReactElement,
  useEffect,
  useRef,
  useState,
} from 'react';
import classNames from 'classnames';
import Input, { InputProps } from '../input/input';
import Icon from '../icon/icon';
import Transition from '../transition/transition';
import useDebounce from '../../hooks/useDebounce';
import useClickOutside from '../../hooks/useClickOutside';

interface DataSourceObject {
  value: string;
}
export type DataSourceType<T = Record<string, unknown>> = T & DataSourceObject;

export interface AutoCompleteProps extends Omit<InputProps, 'onSelect'> {
  fetchSuggestions?: (keyword: string) => DataSourceType[] | Promise<DataSourceType[]>;
  onSelect?: (item: DataSourceType) => void;
  renderOption?: (item: DataSourceType) => ReactElement;
}

export const AutoComplete: FC<AutoCompleteProps> = (props) => {
  const { fetchSuggestions, onSelect, renderOption, value, className, ...restProps } = props;
  const classes = classNames('xy-auto-complete', className);

  const [inputValue, setInputValue] = useState(value as string);
  const [suggestions, setSuggestions] = useState<DataSourceType[]>([]);
  const [loading, setLoading] = useState(false);
  const [showDropdown, setShowDropdown] = useState(false);
  const [highlightIndex, setHighlightIndex] = useState(-1);

  const triggerSearch = useRef(false);
  const componentRef = useRef<HTMLDivElement>(null);

  const debounceValue = useDebounce<string>(inputValue);
  useClickOutside(componentRef, (event: MouseEvent) => {
    setSuggestions([]);
  });

  useEffect(() => {
    if (debounceValue && triggerSearch.current) {
      setSuggestions([]);
      const results = fetchSuggestions && fetchSuggestions(debounceValue);
      if (results instanceof Promise) {
        setLoading(true);
        results.then((data) => {
          setLoading(false);
          setSuggestions(data);
          if (data.length > 0) {
            setShowDropdown(true);
          }
        });
      } else {
        setSuggestions(results!);
        setShowDropdown(true);
        if (results!.length > 0) {
          setShowDropdown(true);
        }
      }
    } else {
      setShowDropdown(false);
    }
    setHighlightIndex(-1);
  }, [debounceValue]);

  const highlight = (index: number) => {
    if (index < 0) index = 0;
    if (index >= suggestions.length) {
      index = suggestions.length - 1;
    }
    setHighlightIndex(index);
  };
  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value.trim();
    setInputValue(value);
    triggerSearch.current = true;
  };
  const handleSelect = (item: DataSourceType) => {
    setInputValue(item.value);
    setShowDropdown(false);
    // setSuggestions([]);
    onSelect && onSelect(item);
    triggerSearch.current = false;
  };
  const handleKeyDown = (e: KeyboardEvent<HTMLElement>) => {
    switch (e.code) {
      case 'Enter':
        suggestions[highlightIndex] && handleSelect(suggestions[highlightIndex]);
        break;
      case 'Escape':
        setShowDropdown(false);
        // setSuggestions([]);
        break;
      case 'PageUp':
        highlight(highlightIndex - 1);
        break;
      case 'PageDown':
        highlight(highlightIndex + 1);
        break;
      default:
        break;
    }
  };

  const renderTemplate = (item: DataSourceType) => {
    return renderOption ? renderOption(item) : item.value;
  };
  const generateDropdown = () => {
    return (
      <Transition
        in={showDropdown || loading}
        animation="zoom-in-top"
        timeout={300}
        onExited={() => {
          setSuggestions([]);
        }}
      >
        <ul className="xy-suggestion-list">
          {loading && (
            <div className="xy-suggestions-loading-icon">
              <Icon icon="spinner" spin />
            </div>
          )}
          {suggestions.map((item, index) => {
            const suggestionClasses = classNames('xy-suggestion-item', {
              'is-active': index === highlightIndex,
            });
            return (
              <li
                key={`${item.value}-${index}`}
                className={suggestionClasses}
                onClick={() => handleSelect(item)}
              >
                {renderTemplate(item)}
              </li>
            );
          })}
        </ul>
      </Transition>
    );
  };

  return (
    <div className={classes} ref={componentRef}>
      <Input
        value={inputValue}
        onChange={handleChange}
        onKeyDown={handleKeyDown}
        {...restProps}
      ></Input>
      {generateDropdown()}
    </div>
  );
};

// packages/vue3xy/src/components/autoComplete/autoComplete.vue
<!--
 * @Author: Chengbotao
 * @Date: 2022-11-24 12:50:54
-->
<template>
    <div ref="xyAutoComplete" :class="classes">
        <xyInput v-bind="$attrs" ref="xyAutoCompleteInput" v-model="inputValue" @input="handleInput" @blur="handleBlur" @keydown="handleKeyDown">
        </xyInput>
        <Transition name="zoom-in-top">
            <ul v-if="suggestions.length" class="xy-suggestion-list">
                <li v-for="(item, index) in suggestions" :key="item.value + '-' + index"
                    :class="['xy-suggestion-item', { 'is-active': index === highlightIndex }]"
                    @click="handleSelect(item)">
                    <template v-if="!slots.suggestionItem">
                        {{ item.value }}
                    </template>
                    <slot name="suggestionItem" :scope="item"></slot>
                </li>
            </ul>
            <div v-else-if="loading" class="xy-suggestion-list">
                <div class ="xy-suggestions-loading-icon">
                    <xyIcon icon="spinner" spin />
                </div>
            </div>
        </Transition>
    </div>
</template>

<script setup lang="ts">
import { ref, computed, useSlots } from "vue";
import classNames from 'classnames';
import { useClickOutside } from "../../hooks/useClickOutside";
import { useDebounce } from "../../hooks/useDebounce";

defineOptions({
    name: 'XyAutoComplete',
    inheritAttrs: false,
})

interface DataSourceObject {
    value: string;
}
type DataSourceType<T = Record<string, unknown>> = T & DataSourceObject;

interface AutoCompleteProps {
    fetchSuggestions: (keyword: string) => DataSourceType[] | Promise<DataSourceType[]>;
    modelValue?: string | number;
    className?: string
}

interface AutoCompleteEmits {
    (event: "select", payload: DataSourceType): void
    (event: "update:modelValue", payload: string): void
}

// ref
const xyAutoComplete = ref<HTMLDivElement>();
useClickOutside(xyAutoComplete, (event: MouseEvent) => {
    suggestions.value = [];
})

// slots
const slots = useSlots();

// Props
const props = withDefaults(defineProps<AutoCompleteProps>(), {
});

// Emits
const emits = defineEmits<AutoCompleteEmits>();

// data
const inputValue = ref(props.modelValue);
const suggestions = ref<DataSourceType[]>([]);
const loading = ref(false);
const highlightIndex = ref(-1);
// const showDropdown = ref(false);
// const triggerSearch = ref(false);


// computed
const classes = computed(() => {
    return classNames("xy-auto-complete", props.className);
});

// methods
const handleInput = useDebounce((event: Event) => {
    inputValue.value = (event.target as HTMLInputElement).value.trim();
    // triggerSearch.value = true;
    const results = props.fetchSuggestions(inputValue.value);
    if (results instanceof Promise) {
        loading.value = true;
        results.then((data) => {
            loading.value = false;
            suggestions.value = data;
        });
    } else {
        suggestions.value = results;
    }
}, 300)
const handleBlur = ()=>{
    inputValue.value = props.modelValue as string;
}
const handleSelect = (item: DataSourceType) => {
    inputValue.value = item.value;
    suggestions.value = [];
    // triggerSearch.value = false;
    highlightIndex.value = -1
    emits("select", item);
    emits("update:modelValue", item.value)
}
const highlight = (index: number) => {
    if (index < 0) index = 0;
    if (index >= suggestions.value.length) {
        index = suggestions.value.length - 1;
    }
    highlightIndex.value = index;
};
const handleKeyDown = (event: KeyboardEvent) => {
    switch (event.code) {
        case 'Enter':
            suggestions.value[highlightIndex.value] && handleSelect(suggestions.value[highlightIndex.value]);
            break;
        case 'Escape':
            suggestions.value = [];
            break;
        case 'ArrowUp':
            highlight(highlightIndex.value - 1);
            break;
        case 'ArrowDown':
            highlight(highlightIndex.value + 1);
            break;
        default:
            break;
    }
};
</script>
