// packages/vue3xy/src/components/button/button.vue
<!--
 * @Author: Chengbotao
 * @Date: 2022-10-11 11:22:01
-->
<template>
    <button v-if="!isLink" key="button" v-bind="$attrs" :disabled="disabled" :class="classes" @click="handleClick">
        <slot></slot>
    </button>
    <a v-else key="a" v-bind="$attrs" :href="href" :class="classes" @click="handleClick">
        <slot></slot>
    </a>
</template>

<script setup lang="ts">
import { computed } from "vue";
import classNames from "classnames";

defineOptions({
    name: 'XyButton',
    inheritAttrs: false,
})

type ButtonSize = "lg" | "sm";
type ButtonType = "primary" | "default" | "danger" | "link";

interface ButtonProps {
    disabled?: boolean
    href?: string
    className?: string
    size?: ButtonSize
    btnType?: ButtonType
}

interface ButtonEmits {
    (event: "click", payload: MouseEvent): void
}

// Props
const props = withDefaults(defineProps<ButtonProps>(), {
    btnType: "default"
});

// Emits
const emits = defineEmits<ButtonEmits>();

// computed
const classes = computed(() => {
    return classNames("xy-button", props.className, {
        [`xy-button-${props.btnType}`]: props.btnType,
        [`xy-button-${props.size}`]: props.size,
        disabled: props.btnType === "link" && props.disabled,
    });
});

const isLink = computed(() => {
    return props.btnType === "link" && !!props.href;
})

// methods
const handleClick = (event: MouseEvent) => {
    emits("click", event)
}

// public 方法
defineExpose({})

</script>

// packages/reactxy/src/components/button/button.tsx
/*
 * @Author: Chengbotao
 * @Date: 2022-10-18 09:47:54
 */
import React, { FC, AnchorHTMLAttributes, ButtonHTMLAttributes } from 'react';
import classNames from 'classnames';

export type ButtonSize = 'lg' | 'sm';
export type ButtonType = 'primary' | 'default' | 'danger' | 'link';

export interface ButtonProps
  extends Partial<ButtonHTMLAttributes<HTMLElement> & AnchorHTMLAttributes<HTMLElement>> {
  /** 设置 Button 禁用 */
  disabled?: boolean;
  /** 设置 Button 尺寸 */
  size?: ButtonSize;
  /** 设置 Button 类型 */
  btnType?: ButtonType;
  /** 当 Button 为 link 类型时的地址 */
  href?: string;
  /** 自定义 css 类名 */
  className?: string;
  children?: React.ReactNode;
}

/**
 * Button 组件
 *
 *
 */
export const Button: FC<ButtonProps> = (props) => {
  const { btnType, disabled, className, size, href, children, ...restProps } = props;
  const classes = classNames('xy-button', className, {
    [`xy-button-${btnType}`]: btnType,
    [`xy-button-${size}`]: size,
    disabled: btnType === 'link' && disabled,
  });

  if (btnType === 'link' && href) {
    return (
      <a className={classes} href={href} {...restProps}>
        {children}
      </a>
    );
  } else {
    return (
      <button className={classes} disabled={disabled} {...restProps}>
        {children}
      </button>
    );
  }
};

Button.defaultProps = {
  disabled: false,
  btnType: 'default',
};

export default Button;
